---
meta:
  vm_types:
    default:
      dev:  (( grab params.vm_types.default.dev  || "t3.medium" ))
      prod: (( grab params.vm_types.default.prod || "m6i.large" ))
    compilation:
      dev:  (( grab params.vm_types.compilation.dev  || "t3.large" ))
      prod: (( grab params.vm_types.compilation.prod || "c6i.xlarge" ))
    bosh:
      dev:  (( grab params.vm_types.bosh.dev  || "t3.large" ))
      prod: (( grab params.vm_types.bosh.prod || "m6i.2xlarge" ))
    concourse:
      dev:  (( grab params.vm_types.concourse.dev  || "t3.medium" ))
      prod: (( grab params.vm_types.concourse.prod || "m6i.large" ))
    concourse-worker:
      dev:  (( grab params.vm_types.concourse-worker.dev  || "t3.medium" ))
      prod: (( grab params.vm_types.concourse-worker.prod || "m6i.large" ))
    api:
      dev:  (( grab params.vm_types.api.dev  || "t3.medium" ))
      prod: (( grab params.vm_types.api.prod || "m6i.xlarge" ))
    as-api:
      dev:  (( grab params.vm_types.as-api.dev  || "t3.medium" ))
      prod: (( grab params.vm_types.as-api.prod || "m6i.large" ))
    as-actors:
      dev:  (( grab params.vm_types.as-actors.dev  || "t3.medium" ))
      prod: (( grab params.vm_types.as-actors.prod || "m6i.large" ))
    as-metrics:
      dev:  (( grab params.vm_types.as-metrics.dev  || "t3.medium" ))
      prod: (( grab params.vm_types.as-metrics.prod || "m6i.xlarge" ))
    as-nozzle:
      dev:  (( grab params.vm_types.as-nozzle.dev  || "t3.medium" ))
      prod: (( grab params.vm_types.as-nozzle.prod || "m6i.xlarge" ))
    app-scheduler:
      dev:  (( grab params.vm_types.app-scheduler.dev  || "t3.medium" ))
      prod: (( grab params.vm_types.app-scheduler.prod || "m6i.large" ))
    bbs:
      dev:  (( grab params.vm_types.bbs.dev  || "t3.medium" ))
      prod: (( grab params.vm_types.bbs.prod || "m6i.xlarge" ))
    blobstore:
      dev:  (( grab params.vm_types.blobstore.dev  || "t3.medium" ))
      prod: (( grab params.vm_types.blobstore.prod || "m6i.large" ))
    cc-worker:
      dev:  (( grab params.vm_types.cc-worker.dev  || "t3.medium" ))
      prod: (( grab params.vm_types.cc-worker.prod || "m6i.large" ))
    credhub:
      dev:  (( grab params.vm_types.credhub.dev  || "t3.medium" ))
      prod: (( grab params.vm_types.credhub.prod || "r6i.large" ))
    diego-api:
      dev:  (( grab params.vm_types.diego-api.dev  || "t3.large" ))
      prod: (( grab params.vm_types.diego-api.prod || "c6i.2xlarge" ))
    diego-cell:
      dev:  (( grab params.vm_types.diego-cell.dev  || "t3.large" ))
      prod: (( grab params.vm_types.diego-cell.prod || "r6i.2xlarge" ))
    doppler:
      dev:  (( grab params.vm_types.doppler.dev  || "t3.medium" ))
      prod: (( grab params.vm_types.doppler.prod || "c6i.xlarge" ))
    errand:
      dev:  (( grab params.vm_types.errand.dev  || "t3.medium" ))
      prod: (( grab params.vm_types.errand.prod || "m6i.large" ))
    haproxy:
      dev:  (( grab params.vm_types.haproxy.dev  || "t3.medium" ))
      prod: (( grab params.vm_types.haproxy.prod || "m6i.xlarge" ))
    log-api:
      dev:  (( grab params.vm_types.log-api.dev  || "t3.medium" ))
      prod: (( grab params.vm_types.log-api.prod || "c6i.xlarge" ))
    loggregator:
      dev:  (( grab params.vm_types.loggregator.dev  || "t3.medium" ))
      prod: (( grab params.vm_types.loggregator.prod || "m6i.xlarge" ))
    nats:
      dev:  (( grab params.vm_types.nats.dev  || "t3.medium" ))
      prod: (( grab params.vm_types.nats.prod || "m6i.large" ))
    postgres:
      dev:  (( grab params.vm_types.postgres.dev  || "t3.medium" ))
      prod: (( grab params.vm_types.postgres.prod || "m6i.xlarge" ))
    router:
      dev:  (( grab params.vm_types.router.dev  || "t3.medium" ))
      prod: (( grab params.vm_types.router.prod || "c6i.xlarge" ))
    scheduler:
      dev:  (( grab params.vm_types.scheduler.dev  || "t3.medium" ))
      prod: (( grab params.vm_types.scheduler.prod || "m6i.large" ))
    syslogger:
      dev:  (( grab params.vm_types.syslogger.dev  || "t3.medium" ))
      prod: (( grab params.vm_types.syslogger.prod || "m6i.xlarge" ))
    tcp-router:
      dev:  (( grab params.vm_types.tcp-router.dev  || "t3.medium" ))
      prod: (( grab params.vm_types.tcp-router.prod || "c6i.xlarge" ))
    uaa:
      dev:  (( grab params.vm_types.uaa.dev  || "t3.large" ))
      prod: (( grab params.vm_types.uaa.prod || "c6i.large" ))
    shield:
      dev:  (( grab params.vm_types.shield.dev  || "t3.medium" ))
      prod: (( grab params.vm_types.shield.prod || "m6i.xlarge" ))
    blacksmith:
      dev:  (( grab params.vm_types.blacksmith.dev  || "t3.medium" ))
      prod: (( grab params.vm_types.blacksmith.prod || "m6i.large" ))
    blacksmith-redis-small:
      dev:  (( grab params.vm_types.blacksmith-redis-small.dev  || "t3.medium" ))
      prod: (( grab params.vm_types.blacksmith-redis-small.prod || "c6i.large" ))
    blacksmith-redis-medium:
      dev:  (( grab params.vm_types.blacksmith-redis-medium.dev  || "t3.medium" ))
      prod: (( grab params.vm_types.blacksmith-redis-medium.prod || "c6i.xlarge" ))
    blacksmith-redis-large:
      dev:  (( grab params.vm_types.blacksmith-redis-large.dev  || "t3.large" ))
      prod: (( grab params.vm_types.blacksmith-redis-large.prod || "c6i.2xlarge" ))
    blacksmith-rabbitmq-small:
      dev:  (( grab params.vm_types.blacksmith-rabbitmq-small.dev  || "t3.small" ))
      prod: (( grab params.vm_types.blacksmith-rabbitmq-small.prod || "c6i.large" ))
    blacksmith-rabbitmq-medium:
      dev:  (( grab params.vm_types.blacksmith-rabbitmq-medium.dev  || "t3.medium" ))
      prod: (( grab params.vm_types.blacksmith-rabbitmq-medium.prod || "c6i.xlarge" ))
    blacksmith-rabbitmq-large:
      dev:  (( grab params.vm_types.blacksmith-rabbitmq-large.dev  || "t3.large" ))
      prod: (( grab params.vm_types.blacksmith-rabbitmq-large.prod || "c6i.2xlarge" ))
    blacksmith-postgres-small:
      dev:  (( grab params.vm_types.blacksmith-postgres-small.dev  || "t3.small" ))
      prod: (( grab params.vm_types.blacksmith-postgres-small.prod || "c6i.large" ))
    blacksmith-postgres-medium:
      dev:  (( grab params.vm_types.blacksmith-postgres-medium.dev  || "t3.medium" ))
      prod: (( grab params.vm_types.blacksmith-postgres-medium.prod || "c6i.xlarge" ))
    blacksmith-postgres-large:
      dev:  (( grab params.vm_types.blacksmith-postgres-large.dev  || "t3.large" ))
      prod: (( grab params.vm_types.blacksmith-postgres-large.prod || "c6i.2xlarge" ))
    windows-cell:
      dev:  (( grab params.vm_types.windows-cell.dev  || "t3.large" ))
      prod: (( grab params.vm_types.windows-cell.prod || "r6i.2xlarge" ))

  disk_sizes:
    default:
      dev:  (( grab params.disk_types.default.size || 32768 ))
      prod: (( grab params.disk_types.default.size || 65536 ))
    bosh:
      dev:  (( grab params.disk_types.bosh.size || 32768 ))
      prod: (( grab params.disk_types.bosh.size || 65536 ))
    blobstore:
      dev:  (( grab params.disk_types.blobstore.size || 32768 ))
      prod: (( grab params.disk_types.blobstore.size || 524288 ))
    postgres:
      dev:  (( grab params.disk_types.postgres.size || 16384 ))
      prod: (( grab params.disk_types.postgres.size || 81920 ))
    blacksmith:
      dev:  (( grab params.disk_types.blacksmith.size || 16384 ))
      prod: (( grab params.disk_types.blacksmith.size || 65536 ))
    blacksmith-redis-small:
      dev:  (( grab params.disk_types.blacksmith-redis-small.size || 8192 ))
      prod: (( grab params.disk_types.blacksmith-redis-small.size || 32768 ))
    blacksmith-redis-medium:
      dev:  (( grab params.disk_types.blacksmith-redis-medium.size || 16384 ))
      prod: (( grab params.disk_types.blacksmith-redis-medium.size || 65536 ))
    blacksmith-redis-large:
      dev:  (( grab params.disk_types.blacksmith-redis-large.size || 32768 ))
      prod: (( grab params.disk_types.blacksmith-redis-large.size || 131072 ))
    blacksmith-rabbitmq-small:
      dev:  (( grab params.disk_types.blacksmith-rabbitmq-small.size || 8192 ))
      prod: (( grab params.disk_types.blacksmith-rabbitmq-small.size || 32768 ))
    blacksmith-rabbitmq-medium:
      dev:  (( grab params.disk_types.blacksmith-rabbitmq-medium.size || 16384 ))
      prod: (( grab params.disk_types.blacksmith-rabbitmq-medium.size || 65536 ))
    blacksmith-rabbitmq-large:
      dev:  (( grab params.disk_types.blacksmith-rabbitmq-large.size || 32768 ))
      prod: (( grab params.disk_types.blacksmith-rabbitmq-large.size || 131072 ))
    blacksmith-postgres-small:
      dev:  (( grab params.disk_types.blacksmith-postgres-small.size || 8192 ))
      prod: (( grab params.disk_types.blacksmith-postgres-small.size || 32768 ))
    blacksmith-postgres-medium:
      dev:  (( grab params.disk_types.blacksmith-postgres-medium.size || 16384 ))
      prod: (( grab params.disk_types.blacksmith-postgres-medium.size || 65536 ))
    blacksmith-postgres-large:
      dev:  (( grab params.disk_types.blacksmith-postgres-large.size || 32768 ))
      prod: (( grab params.disk_types.blacksmith-postgres-large.size || 131072 ))
    shield:
      dev:  (( grab params.disk_types.shield.size || 8192 ))
      prod: (( grab params.disk_types.shield.size || 16384 ))
    minio:
      dev:  (( grab params.disk_types.minio.size || 32768 ))
      prod: (( grab params.disk_types.minio.size || 262144 ))

